CodeMontageHQ/codemontage

- app/models/event.rb
- app/models/featured_project.rb
- app/models/project.rb
- db/migrate/20150105164219_create_featured_projects.rb
- db/migrate/20150108141354_add_unique_index_to_featured_projects.rb
- db/schema.rb
This PR allows event-specific featured projects to exist in the app. Purely backend work here:
* new FeaturedProject model
* new featured_projects table
* associations between events and projects, through featured_projects
Check it out in a console near you!
```ruby
> event = Event.create(name: "Test Event", short_code: "fake")
> project = Project.last
> fp = FeaturedProject.new
> fp.event = event
> fp.project = project
> fp.save
```
Future improvements:
> Backend additions (db, models) to allow featured projects for events

- app/admin/events.rb
- app/admin/featured_projects.rb
- app/models/event.rb
- app/models/featured_project.rb
- app/models/project.rb
- db/migrate/20150105164219_create_featured_projects.rb
- db/schema.rb
Building on #291, this PR:
- allows mass assignment of FeaturedProject attributes
- allows events to take nested featured projects attributes
- adds featured projects to admin area
- allows featured projects to be added or edited directly from an event area
:point_down: :point_down: Photographic evidence below! :point_down: :point_down:
*Featured Projects in the Admin Menu*
*Featured Projects index page*
*Featured Projects new page*
*Featured Projects sidebar in the Events show page*
*Featured Projects nested inputs in the Events edit page*
> Allow admins to create featured projects

- app/views/projects/_project.html.erb
- app/views/projects/index.html.erb
While we're partialling things all willy-nilly, here's a quick refactor of the projects index.
Here's a screenshot of it looking exactly the same:
> Projects index refactor (to use a partial)

- app/assets/stylesheets/events.css.scss
- app/controllers/events_controller.rb
- app/controllers/projects_controller.rb
- app/models/user.rb
- app/views/events/show.html.erb
- app/views/projects/_project.html.erb
Uses the existing project partial to show featured projects on an individual events show page
This required refactoring the `@favorite_projects` instance variable from `UsersController` to `User#favorited_projects`.
*Featured projects sitting pretty on events show page*
> Add featured projects to events show page

- Gemfile
- Gemfile.lock
- spec/factories/events.rb
- spec/factories/featured_projects.rb
- spec/factories/organizations.rb
- spec/factories/projects.rb
- spec/models/event_spec.rb
- spec/models/featured_project_spec.rb
- spec/models/project_spec.rb
- spec/spec_helper.rb
- Includes handful of specs meant to be a starting place for testing featured projects
- Adds factory_girl_rails to make testing a join model (like `FeaturedProject`) easier
- Includes (very minimal) factories for all `FeaturedProject`-relevant models: `Event`, `Organization`, & `Project`
Factory_girl_rails was especially necessary because the shoulda-matchers `#validates_uniqueness_of` method requires an instance of the model to exist in the database.
*suite still passes*
> Add simple unit specs for featured_projects

- app/admin/event_registrations.rb
- app/assets/javascripts/application.js
- app/views/home/dashboard/_events.html.erb
Front end change to introduce the concept of check-ins to users and admins. Clearly the ActiveAdmin error handling is still tied to the model name (as seen in the green notice in the screenshot below), but that should change when back end switches are made -- see #295.
*The administrative check-in experience*
*Checking in(!) on the user dashboard*
> Change event "registrations" to "check ins" for users & admins

- app/admin/events.rb
- app/models/event.rb
- db/migrate/20150112145730_add_is_public_to_events.rb
- db/schema.rb
This adds a lil bitty boolean on events to say whether they're public (and thus share-ready) or not. Includes:
- necessary db migration/model changes
- form additions to the admin area
- scope for future frontend/controller changes
*Admin can see public status*
*Admin can change public status*
> Add public flag to events

- app/admin/events.rb
- app/controllers/events_controller.rb
- app/models/event.rb
- db/migrate/20150112145730_add_is_public_to_events.rb
- db/schema.rb
Teensy change that shows only events flagged public on the events index page.
*Three events on the events index*
*But five in the database! And look which ones are marked public!*
> Only show public events on the events index page

- app/assets/javascripts/application.js
- app/assets/javascripts/check_in_prompt.js
- app/assets/stylesheets/events.css.scss
- app/controllers/application_controller.rb
- app/controllers/events_controller.rb
- app/controllers/home_controller.rb
- app/controllers/projects_controller.rb
- app/models/event.rb
- app/views/events/_check_in_prompt.html.erb
- app/views/events/index.html.erb
- app/views/home/index.html.erb
- app/views/projects/index.html.erb
- Adds backend `Event` functionality to return a currently-scheduled event (or nil)
- At times when there is no currently-scheduled event, nothing unusual happens
- At times when there is a currently-scheduled event and the user is logged in:
- the user gets prompted to check in on `/events`, `/projects` & `/` via a modal
- the user gets immediate feedback when the check in has occurred
- the user will not get prompted after they've checked in
It would be nice to have some feature tests for this functionality. One day, some day. But in the meantime, experiential proof:
*On the Events page*
*On the Home page*
*On the Projects page*
*Checked in*
> Create prompt for check ins

- app/models/event.rb
- app/models/event_registration.rb
- app/models/featured_project.rb
- app/models/project.rb
- app/models/user.rb
- spec/cassettes/codemontage_oct_stats.yml
- spec/cassettes/courte_oct_stats.yml
- spec/models/event_registration_spec.rb
- spec/models/featured_project_spec.rb
- spec/models/project_spec.rb
- spec/models/user_spec.rb
Last part and parcel of #311's refactor, now with all the event-related GitHub participation stats you'd been waiting for: `users`, `projects`, `event_registrations`, `featured_projects`, and `events` can all return their GitHub participation metrics as hashes.
> Fetch GitHub stats

- app/admin/projects.rb
- app/assets/stylesheets/projects.css.scss
- app/models/project.rb
- app/views/projects/_project.html.erb
- app/views/projects/show.html.erb
- db/migrate/20150127012233_add_install_url_and_help_url_to_projects.rb
- db/schema.rb
This update gives projects the option to have links to installation directions and/or a help area (chat room, email, etc). It adds these links to the admin areas, as well as the projects partial.
The install link has also been added to the project show page and the news/twitter link has been moved there as well. I think 4 links in a column is the upward limit of these links not looking crowded and distracted, so the help url has not been added to the project show page currently.
Take a peek!
*Projects partial on the index page*
01](https://cloud.githubusercontent.com/assets/2766324/5921311/10e5c452-a611-11e4-9e64-e08766a1eb3f.png)
*Install & help urls in admin areas (edit, show & index)*
*Install url and news/twitter link on project show page*
*New links included with a featured project …
> Add helpful project links

- app/models/event.rb
This PR fixes immediate GitHub stats-related problems. It includes:
- basic error-handling for pesky failing GitHub search queries
- batch GitHub stats processing of event-related resources to avoid GitHub API search rate limit
- memoized stats (`attendee_github_stats`, `project_github_stats`, `github_stats`) to prevent multiple time-draining pulls to the API in a single session
> Avoid GitHub rate limit

- app/views/events/show.html.erb
Issue #324 Modify the rsvp button so that it is positioned about Join us event phrase.
> Modify the events page to show the rsvp before 'Join Us'

- app/views/events/show.html.erb
This PR:
- Adds a blurb from the Code of Conduct to the Events show page (#262)
- Fixes #325 
- Includes screenshots :point_down: :point_down: 
*Code of Conduct blurb*
===
*Related Events section*
> Add Code of Conduct blurb to Events show page

- app/admin/events.rb
This PR adds hints that encourage administrative users to input event start & end times for the UTC time zone. Because check-in prompting is now dependent on accurate start and end times, this has become important.
> Add timezone info to event time inputs

- app/admin/events.rb
- app/models/event.rb
- app/views/events/show.html.erb
- db/migrate/20150209221313_add_schedule_to_events.rb
- db/schema.rb
- Adds schedule to events on database, model, admin, and front end levels
- Shows schedule as raw HTML list items (I figured we could work out the formatting of this a little later.)
- Sets schedule to be a smaller width than most of the Event show page
I would love to have this & the description section to be markdown one day, but alas. Let's :rocket: it.
*Editing a schedule*
*Look at it go!*
*LOOK AT IT GO.*
> Add basic schedules to events

- app/controllers/application_controller.rb
- app/views/layouts/_navigation.html.erb
An easy way to find upcoming events -- the nav bar!
Not sure about adding this database-dependent `before_filter` to every controller - if it creates unnecessary noise - but it works!
*Nav bar with upcoming events*
> Events nav dropdown now holds upcoming events

- config/environments/staging.rb
A slight change that should use Heroku's built-in SSL certificate in staging, to better match production environment.
> Enforce ssl for staging environment

- app/models/event.rb
Fixes #301.
__*before delete*__
__*after delete*__
> Allow event logos to be deleted

- app/models/event.rb
- app/models/favorite_project.rb
Adds a method to `Event` that return the stats on the number of featured projects favorited during the event. It also includes this result in the (now inaccurately-named) `fetch_github_stats` results.
Here's an example call with results at the very bottom:
> Add on-platform favorites of featured projects to Event stats

- app/views/home/project_requirements.html.erb
- app/views/layouts/_navigation.html.erb
- config/routes.rb
This also includes the addition of a link to this on the main nav. Not 100% sure that we want to do this or not, but will leave it up to the team to decide how to move forward.
I'd also like to see a link on `/projects` that references this page somehow. I started incorporating that on this PR, but then decided it was a bit out of scope. Let me know if you'd like me to open another issue with this specific addition. :space_invader: 
Also, let me know if you want screenshots too!
> Adding project requirements page, fixes #341.

- app/assets/stylesheets/events.css.scss
- app/controllers/events_controller.rb
- app/models/event.rb
- app/views/events/index.html.erb
- app/views/events/show.html.erb
I have a branch with these changes here: https://github.com/alexshook/codemontage/tree/update_language_for_past_events
but I'm not totally sure about the language. Here are two screenshots-- let me know about any changes you'd like.
> Update language for past events - for Add date logic to update language when an Event passed #343

- README.md
We have an issue template, and now folks can see it in our docs, near some emojis:
(It won't be in Times New Roman on GitHub, promise!)
> Link to issue template & include requisite emojis in the README

- config/environments/production.rb
- config/environments/staging.rb
This PR configures ActionMailer in staging and production, fixing #303, as suggested by @escobara (Thanks!).
Successfully requested password recovery email:
:heart_eyes:
> Configure ActionMailer in staging and production

- app/controllers/events_controller.rb
- app/views/events/index.html.erb
- db/schema.rb
Addressing the display issues brought up in #390 
- Added public_events to be used in the events index page
- Rearrange the conditionals to always display past events if there are any
I added in some filler text when there are only past events ("There are no upcoming events.") This makes the page look a little bit better and at least informs the user that this IS a place where they can find upcoming events if there are any.
> Fix for Past Events Don't Display Without Upcoming Events - Issue#390
